# This workflow will build and test the Go service with Specmatic contract tests using testcontainers

name: CI Pipeline

on:
  push:
    branches: [ main, feat/testcontainers ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
      # Running tests only on Linux as the application is Dockerized and runs in a Linux container.
      # Windows runners cause issues with Docker networking (e.g., missing bridge plugin) and are unnecessary for containerized apps.
      # Docker is not supported on the MacOS arm64 images. Source: https://github.com/marketplace/actions/setup-docker-on-macos
        os: [ubuntu-latest]
        go: [1.23]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        check-latest: true

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Go Service Docker Image
      run: |
        docker build --platform linux/amd64 -t specmatic-go-service:latest .

    - name: Verify Go Service Build
      working-directory: go-service
      run: |
        go mod download
        go vet ./...
        go build -o service

    - name: Run Contract Tests
      working-directory: go-service
      env:
        SPECMATIC_OAUTH2_TOKEN: ""
        CUSTOM_RESPONSE: "false"
        SPECMATIC_GENERATIVE_TESTS: "true"
        ONLY_POSITIVE: "false"
      run: |
        go test -v -timeout 10m
    - name: Upload Specmatic Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: specmatic-test-results-${{ matrix.os }}-${{ matrix.go }}
        path: |
          build/
        retention-days: 30