# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Pipeline

on:
  push:
    branches: [ main, fix/workflow ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17]
        go: [1.22]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: ${{ matrix.java }}
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
    - name: Build and Test Go Service
      working-directory: main/go-service
      run: |
        go vet ./...
        go test ./...
    - name: Start Go Service (Unix)
      if: runner.os != 'Windows'
      working-directory: main/go-service
      shell: bash
      run: |
        nohup go run . > ../../go-service.log 2>&1 &
        echo "GO_PID=$!" >> $GITHUB_ENV
    - name: Start Go Service (Windows)
      if: runner.os == 'Windows'
      working-directory: main/go-service
      shell: powershell
      run: |
        Start-Process -FilePath "go" -ArgumentList "run","." -WindowStyle Hidden -PassThru | Out-File -FilePath go_pid.txt
        Start-Sleep -Seconds 5
    - name: Run Contract Tests (Maven)
      working-directory: main
      shell: bash
      run: mvn -B test
    - name: Stop Go Service (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: kill $GO_PID
    - name: Stop Go Service (Windows)
      if: runner.os == 'Windows'
      working-directory: main/go-service
      shell: powershell
      run: |
        $pid = Get-Content go_pid.txt | ConvertFrom-Json | Select-Object -ExpandProperty Id
        Stop-Process -Id $pid -Force
        Remove-Item go_pid.txt
