# This workflow will build and test the Go service with Specmatic contract tests using testcontainers

name: CI Pipeline

on:
  push:
    branches: [ main, feat/testcontainers ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        go: [1.23]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        check-latest: true

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Go Service Docker Image
      run: |
        docker build -t specmatic-go-service:latest .

    - name: Verify Go Service Build
      working-directory: go-service
      run: |
        go mod download
        go vet ./...
        go build -o service

    - name: Run Contract Tests with Testcontainers
      working-directory: go-service
      env:
        SPECMATIC_OAUTH2_TOKEN: ""
        CUSTOM_RESPONSE: "false"
        SPECMATIC_GENERATIVE_TESTS: "true"
        ONLY_POSITIVE: "false"
      run: |
        go test -v -timeout 10m

