# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Pipeline

on:
  push:
    branches: [ main, fix/workflow ]
  pull_request:
    branches: [ main ]
# ... existing workflow ...
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17]
        go: [1.22]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: ${{ matrix.java }}
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
    - name: Build and Test Go Service
      working-directory: main/go-service
      run: |
        go vet ./...
        go test ./...
    - name: Start Go Service and Run Contract Tests
      working-directory: main
      shell: ${{ matrix.os == 'windows-latest' && 'pwsh' || 'bash' }}
      env:
        PORT: ":8090"
        SERVER_PORT: "0"
      run: |
        if ("${{ matrix.os }}" -eq "windows-latest") {
          # Windows/PowerShell version
          Set-Location go-service
          Start-Process -NoNewWindow -FilePath "go" -ArgumentList "run ." -PassThru
          $gopid = (Get-Process -Name "go*").Id
          Set-Location ..
          Start-Sleep -Seconds 10
          # Increased memory + updated surefire version
          mvn -B test -Dsurefire.version=3.2.5 -DargLine="-Xmx2048m" -Djacoco.skip=true
          Stop-Process -Id $gopid -Force
        } else {
          # Linux/macOS version
          pushd go-service
          go run . &
          GO_PID=$!
          popd
          sleep 10
          mvn -B test -Dsurefire.version=3.2.5 -DargLine="-Xmx2048m" -Djacoco.skip=true
          kill $GO_PID
        }